version: '3.8'

services:
  db_mysql:
    image: mysql/mysql-server:latest
    container_name: app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    networks:
      - my_network



networks:
  my_network:
    driver: bridge